### ISSUE TITLE
Memory Leak for Assembler Code Generation

### ISSUE THREAD

**Issue by KoppDaniel** [csaq5507/CompilerConstruction#22]
Code example:

void main(){
	int a;
	int b;
	int c;
	a = 1;
	b = 5;
	if ( a < 10) {
	    a = 10;
	} else {
	    a = 10;
	}
	a = 5;
}

**Comment by csaq5507** [comment]
missing    

`    mCc_assembly_delete(ass);
` 

statement in main

**Comment by KoppDaniel** [comment]
na.
 i kriag ba a poor sochn an memleak:

==13699== Conditional jump or move depends on uninitialised value(s)
==13699==    at 0x50A98BC: vfprintf (vfprintf.c:1643)
==13699==    by 0x50B1DE3: fprintf (fprintf.c:32)
==13699==    by 0x4E4E780: mCc_assembly_print (in /root/CLionProjects/CompilerConstruction/build/libmCc.so)
==13699==    by 0x1095E7: main (in /root/CLionProjects/CompilerConstruction/build/mCc)
==13699== 
==13699== Conditional jump or move depends on uninitialised value(s)
==13699==    at 0x4C2DD71: free (vg_replace_malloc.c:530)
==13699==    by 0x4E4E710: mCc_assembly_delete (in /root/CLionProjects/CompilerConstruction/build/libmCc.so)
==13699==    by 0x109607: main (in /root/CLionProjects/CompilerConstruction/build/mCc)
