### ISSUE TITLE
mem leak for "if (!a)" in code generation

### ISSUE THREAD

**Issue by KoppDaniel** [csaq5507/CompilerConstruction#24]
Code example:

void main(){
	int a;
	int b;
	int c;
	a = 1;
	b = 5;
	if (!((a > 10) && (a < 10))) {
	    a = 15;
	}
	else {
	    a = 10;
	}
	a = 5;
}

**Comment by KoppDaniel** [comment]
Also an error is printed

**Comment by csaq5507** [comment]
this should not be supportet. unary op ! = faculty,
faculty of boolean is not supportet??
