### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by csaq5507** [csaq5507/CompilerConstruction#5]

**Comment by KoppDaniel** [comment]
for executing shell commands inside c code:

#include <stdlib.h>

system("some shell command");

----------------------------example---------------------------------------------------------

system("gcc -m32 -S -O0 -fno-stack-protector -fno-asynchronous-unwind-tables ../doc/examples/test.c");
system("gcc -m32 -c test.s");*/

**Comment by csaq5507** [comment]
easy
