### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by csaq5507** [csaq5507/CompilerConstruction#6]

**Comment by csaq5507** [comment]
struct mCc_cfg_list{
	int num_next_nodes;
	int num_prev_nodes;
	struct mCc_cfg_list * next_nodes;
	struct mCc_cfg_list * prev_nodes;
	struct mCc_tac_list * tac_start;
	struct mCc_tac_list * tac_end;
};

**Comment by KoppDaniel** [comment]
done
