### ISSUE TITLE
Arrays in tac

### ISSUE THREAD

**Issue by csaq5507** [csaq5507/CompilerConstruction#9]
I cant see the size of arrays in TAC?!?

**Comment by KoppDaniel** [comment]
Like that?

Or where do you need this information ?

void main()
{
int [10]a;
int b;
b=0;
a[b] = 0;
b=a[5];
}

TAC:

main
ARRAY_PARAM: a0 10
PARAM: b1
COPY: t4 = 0
COPY: b1 = t4
COPY: t2 = b1
COPY: t3 = 0
STORE: a0 t2 t3
COPY: t0 = 5
LOAD: t1 a t0
COPY: b1 = t1
main

**Comment by KoppDaniel** [comment]
Changed to the following at the end: The number at the param entry always indicates the size of the declaration. For a single declaration, it is 1

<FUNCTION START> main
PARAM: a0 10
PARAM: b1 1
COPY: t4 = 0
COPY: b1 = t4
COPY: t2 = b1
COPY: t3 = 0
STORE: a0 t2 t3
COPY: t0 = 5
LOAD: t1 a0 t0
COPY: b1 = t1
<FUNCTION END> main
